version: "3.9"
services:
  proxy:
    image: nginx:alpine
    container_name: rpcproxy
    ports:
      - "8545:80"
    links:
       - ethereum
    volumes:
      - "./rpcproxy/njs:/etc/nginx/njs"
      - "./rpcproxy/logs:/var/log/nginx"
      - "./rpcproxy/nginx.conf:/etc/nginx/nginx.conf"
    restart: always
  ethereum:
    build: geth-clique
    container_name: geth-clique
    restart: always
