version: "3.9"
services:
  proxy:
    image: nginx:stable-alpine
    container_name: rpcproxy
    ports:
      - "8545:80"
    links:
      - ethereum
    volumes:
      - ./rpcproxy/njs:/etc/nginx/njs
      - ./rpcproxy/log:/var/log/nginx
      - ./rpcproxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ethereum
    restart: always
  
  ethereum:
    image: ethereum/client-go:latest
    container_name: geth-clique
    expose:
      - "8545"
    volumes:
      - ./geth-clique:/root/.ethereum
    command: --allow-insecure-unlock --networkid=${NETWORKID} --unlock="0" --password="/root/.ethereum/password.txt" --nodiscover --mine --http --http.api=debug,eth,web3,net --http.addr=0.0.0.0 --http.port=8545 --http.corsdomain='*' --http.vhosts='*'
    restart: always
