version: "3.3"
services:
  geth:
    build: docker/geth
    container_name: ethereum
    expose:
      - "8545"
    volumes:
      - ./config:/config
      - ./data:/data
    restart: always

  proxy:
    build: docker/rpcproxy
    container_name: rpcproxy
    ports:
      - "8545:8545"
    links:
      - geth
    depends_on:
      - geth
    restart: always

  faucet:
    image: chainflag/eth-faucet
    container_name: ethfaucet
    ports:
      - "8080:8080"
    links:
      - geth
    volumes:
      - ./config/keystore:/app/keystore
      - ./config/faucet.yml:/app/config.yml
    depends_on:
      - geth
    restart: always
