version: "3.3"
services:
  geth:
    build: docker/geth
    container_name: ethereum
    expose:
      - "8545"
    volumes:
      - ./config:/root/.ethereum
    restart: always

  proxy:
    build: docker/rpcproxy
    container_name: rpcproxy
    ports:
      - "8545:8545"
    links:
      - geth
    depends_on:
      - geth
    restart: always
