version: "3.3"
services:
  proxy:
    image: nginx:stable-alpine
    container_name: rpcproxy
    ports:
      - "8545:80"
    links:
      - geth
    volumes:
      - ./rpcproxy/njs:/etc/nginx/njs
      - ./rpcproxy/log:/var/log/nginx
      - ./rpcproxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - geth
    restart: always
  
  geth:
    build: geth-clique
    container_name: geth-clique
    expose:
      - "8545"
    volumes:
      - ./geth-clique:/root/.ethereum
    restart: always
